name: Test Locust Load Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: esmaeilram/locust-test@main
        with:
          LOCUSTFILE: "locustfile.py"
          URL:  "https://google.com"
          USERS: "6"
          RATE: "6"
          RUNTIME: "10s"
